<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Microshop.Catalog.Domain\Microshop.Catalog.Domain.csproj" />
      <ProjectReference Include="..\Microshop.SharedLibrary\Microshop.SharedLibrary.csproj" />
    </ItemGroup>

</Project>
